name: NPM Builds

on:
  # push:
  #   branches: [main, master]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      SITE_LOCALE: "$SITE_LOCALE"
      SITE_TITLE: "$SITE_TITLE"
      SITE_AUTHOR: "$SITE_AUTHOR"
      CODEPEN_USER: "$CODEPEN_USER"
      CODEPEN_NAME: "$CODEPEN_NAME"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install, build, and upload your site output
        uses: withastro/action@v0
        with:
          node-version: 19
          package-manager: npm
