name: Build for GitHub Pages

on:
  # push:
  #   branches: [main, master]
  # pull_request:
  #   branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SITE_LOCALE: "$SITE_LOCALE"
      SITE_TITLE: "$SITE_TITLE"
      SITE_AUTHOR: "$SITE_AUTHOR"
      CODEPEN_USER: "$CODEPEN_USER"
      CODEPEN_NAME: "$CODEPEN_NAME"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install, build, and upload your site
        uses: withastro/action@v1
        with:
          node-version: 19
          package-manager: pnpm@latest
