name: Node.js CI Build

on:
  # push:
  #   branches: [main, master]
  # pull_request:
  #   branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: npm ci
      - name: Build
        env:
          SITE_LOCALE: "$SITE_LOCALE"
          SITE_TITLE: "$SITE_TITLE"
          SITE_AUTHOR: "$SITE_AUTHOR"
          CODEPEN_USER: "$CODEPEN_USER"
          CODEPEN_NAME: "$CODEPEN_NAME"
        run: npm run build --if-present
      # - name: Test
      #   run: npm test
